[smtc2web.theme]
name  = "spotify"
version = "0.1.0"
description = "spotify theme for smtc2web"
author = "AkarinLiu"
repository = "https://github.com/AkarinLiu/smtc2web-theme-spotify.git"
tags = ["vue","simple","spotify"]
icon = "icon.png"
screenshot = "screenshot.png"
